name: "Unit Test"
on: ["push"]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Run unit tests
        run: go test -v ./...

      - name: Build binary
        run: go install ./cmd/ltx

